#' trainTree Function
#'
#' This function trains a decision tree model based on patient data, which can either be gene expression levels or a binary matrix indicating mutations.
#'
#' @param PatientData A matrix representing either gene expression data or mutation information.
#'                     This matrix can be binary (for mutational data) or continuous (for expression data).
#' @param PatientSensitivity A numeric vector indicating drug response values.
#'                           Higher values suggest greater drug resistance and, consequently, less sensitivity.
#'                           This vector can represent various measures of drug response, such as IC50,
#'                           area under the drug response curve (AUC), or other relevant metrics.
#'                           Depending on the interpretation of the sensitivity response, the user may need to adjust the sign of the data.
#' @param minbucket An integer specifying the minimum number of patients required in a node to allow for a split.
#'
#' @return An object of class 'party' representing the trained decision tree, with the assigned treatments for each node.
#'
#' @examples
#'
#' \dontrun{
#'   # Basic example of using the trainTree function with mutational data
#'   data(DataODT.rda)
#'   ODTmut <- trainTree(PatientData = mutations_w12, 
#'                       PatientSensitivity = drug_response_w12,
#'                       minbucket = 10)
#'   plot(ODTmut)
#'
#'   # Example using gene expression data instead
#'   data(DataODT.rda)
#'   ODTExp <- trainTree(PatientData = expression_w34,
#'                       PatientSensitivity = drug_response_w34,
#'                       minbucket = 20)
#'   plot(ODTExp)
#' }
#'
#' @import matrixStats
#' @import partykit
#' @export

trainTree <- function(PatientData,
                      PatientSensitivity,
                      minbucket = 20) {
  # Check if the PatientData matrix is binary (i.e., contains only two unique values)
  if (length(unique(c(unlist(PatientData)))) == 2) {
    # For binary data (mutational data):
    
    # Transform the PatientData to start from 1
    PatientData <- PatientData - min(PatientData) + 1L
    # Set the mode of PatientData to integer for compatibility with the tree-growing function
    PatientData <- apply(PatientData, 2, as.integer)
    
    # Grow the decision tree using the mutational data
    nodes <- growtreeMut(id = 1L,
                         PatientSensitivity,
                         PatientData,
                         minbucket = minbucket)
  } else {
    # For non-binary data (gene expression data):
    
    # Transpose the PatientData matrix to have genes as columns and patients as rows
    PatientData <- t(PatientData)
    
    # Grow the decision tree using the gene expression data
    nodes <- growtreeExp(id = 1L,
                         PatientSensitivity,
                         PatientData,
                         minbucket = minbucket)
  }
  
  # Create a party object from the nodes generated by the tree-growing functions
  tree <- party(nodes, data = as.data.frame(PatientData))
  
  # Remove additional node information from the tree object
  tree$node$info <- NULL
  
  # Return the trained decision tree
  return(tree)
}